### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by mbreemhaar** [netarchivesuite/solrwayback#192] opened 2021-10-14 09:54 UTC
Hi,

I have some warc files created using [warcit](https://github.com/webrecorder/warcit). Somehow after indexing (without errors or warnings), I can't find any page included in it on SolrWayback. I tested the files using [pywb](https://github.com/webrecorder/pywb) but that all works fine. I also tested some other warc files in SolrWayback and they work fine too. Now I'm not sure if there is a problem with my files or if it is a bug in SolrWayback. 

I attached one of my warc files: (removed link)

Can anybody help me? I would really like to know why this is not working. Thanks!

**Comment by tokee** [comment] 2021-10-15 09:29
Summary: This was due to a shortcoming in webarchive-discovery. It is fixed in the mentioned pull request and will either be merged to the fork used by SolrWayback when the pull request is accepted or @thomasegense gets impatient and does it directly.

Thank you very much for the bug report at the nice sample data, @mbreemhaar

**Comment by thomasegense** [comment] 2021-10-15 10:54
Also it will require several changes in SolrWayback as well. Playback depends on information in http header (status code, encoding) etc. and all that information is missing here. But with Toke's fix there was 47 documents generated in Solr (2  documents discarded for some reason).  I hope to get time to look into it next week if it is an easy fix.

**Comment by mbreemhaar** [comment] 2021-10-19 12:48
@thomasegense It would be great if you could send me the custom software bundle with the fix. Unfortunately the collection I'm working with is not my own data, so I'll have to ask the owner for permission to have it added to the unit-test resources. I will let you know as soon as possible if this is okay.

**Comment by mkrzmr** [comment] 2022-06-25 15:27
Hello, I think I am having the same problem. Could you reupload the patch please?

**Comment by thomasegense** [comment] 2022-06-25 16:55
@mkrzmr  The latest 4.3.2 release has the fix included.
Is it not working? Can you then share the WARC file?
Or give me the start if the WARC file? Warc meta data + first two headers for  first record.

**Comment by mkrzmr** [comment] 2022-06-26 16:22
Sure, here is the [file](https://drive.google.com/file/d/1mWftG9oI1BbiL6stOWdcF5yNAlSvhxXH/view?usp=sharing). 

It's just a random warc I made with the instructions from the documentation to see if the issue was with my files. But so far, I have not been able to index a warc.

And here is part of the log:
`Parsing Archive File [1/1]:warcs1/www.iana.org.warc.gz
WARN  WARCIndexer - Invalid status line: null@298
WARN  WARCIndexer - Invalid status line: null@40024
WARN  WARCIndexer - Invalid status line: null@40334
WARN  WARCIndexer - Invalid status line: null@42113
WARN  WARCIndexer - Invalid status line: null@44541
WARN  WARCIndexer - Invalid status line: null@46431
WARN  WARCIndexer - Invalid status line: null@46813
WARN  WARCIndexer - Invalid status line: null@49678
WARN  WARCIndexer - Invalid status line: null@52068
WARN  WARCIndexer - Invalid status line: null@55623
WARN  WARCIndexer - Invalid status line: null@57798
WARN  WARCIndexer - Invalid status line: null@65220
WARN  WARCIndexer - Invalid status line: null@68046
WARN  WARCIndexer - Invalid status line: null@68433
WARN  WARCIndexer - Invalid status line: null@70862
WARN  WARCIndexer - Invalid status line: null@77926
WARN  WARCIndexer - Invalid status line: null@80239
WARN  WARCIndexer - Invalid status line: null@83229
WARN  WARCIndexer - Invalid status line: null@230412
WARN  WARCIndexer - Invalid status line: null@263287
WARN  WARCIndexer - Invalid status line: null@294448
WARN  WARCIndexer - Invalid status line: null@294795
WARN  WARCIndexer - Invalid status line: null@299541`

**Comment by thomasegense** [comment] 2022-06-26 17:13
@mkrzmr Thanks for the WARC file.

I can confirm I have identical problems as you have.  I have reopened the issue.

The WARC type is 'resource'  which is what this original issue was about.

I will look into it tomorrow at work. Maybe type 'resource' was not fixed entirely  or merge/regression error.

What documentation did you use to create the WARC file? It has been created from a file system and not from a WEB harvest.
(WebRecorder, Heritrix,wget etc.)

If you just want to  try to SolrWayback, you can harvest some websites  using the wget examle described in the README page for SolrWayback and index them.

/Thomas

**Comment by mkrzmr** [comment] 2022-06-27 08:23
Thanks Thomas,

the warc file as created with Warcit:

`For example, the following example will download a simple web site via wget (for simplicity, this retrieves one level deep only), then use warcit to convert to www.iana.org.warc.gz:

wget -l 1 -r www.iana.org/
warcit http://www.iana.org/ ./www.iana.org/

The WARC www.iana.org.warc.gz should now have been created!`

I have a collection made from local files I want to import, just made the iana.org file to try and see where the error comes from. Seems to be warcit always adds 'resource'

/Michael

**Comment by thomasegense** [comment] 2022-06-27 08:30
@mkrzmr Thanks, that explains why these files are still made. 
But wget can create WARC-files directly. See the solrwayback README at: https://github.com/netarchivesuite/solrwayback
and scroll down to :
5) CREATING YOUR OWN WARCS - HARVESTING WITH WGET
This will also gives you a lot more options such as follow links 1 level.

The advantage using a web-harvest is the HTTP header will be included. This will give information about encoding,
http status. If resources are moved (3xx codes) this information will also be saved and is important for correct playback.

Still the issue needs to be resolved of course and hope it can be solved today.

**Comment by thomasegense** [comment] 2022-06-28 10:09
@mkrzmr 
Hi, there was indeed a merging error. It will be part of the comming 3.5.0 release.
You can download the warc-indexer here: https://drive.google.com/file/d/13aza6dO2MXBmxvpxc5fN94mZLW4gGShF/view?usp=sharing

Still if you make your own WARC-files I will recommend using a Web harvester or just WGET. 
Please tell me if it works for you :) Then I can close this again, for good this time :)

**Comment by mkrzmr** [comment] 2022-06-28 11:37
Thank you, I can confirm the issue is resolved

**Comment by thomasegense** [comment] 2022-06-28 11:40
Thanks, closing again. 
3.5.0 will be released in some weeks I hope.

**Closed by thomasegense** 2022-06-28 11:40 UTC
