### ISSUE TITLE
Website does not show correctly

### ISSUE THREAD

**Issue by mbreemhaar** [netarchivesuite/solrwayback#230] opened 2022-08-11 08:37 UTC
Hi,

I have a problem with some WARC files in my collection. For example, [this file](https://drive.google.com/file/d/18HlPVOWFf_QM4cY3BkI3cP4A_7Fu4rng/view?usp=sharing) I have from [www.pvda.nl](https://www.pvda.nl) does not display correctly. I checked whether the problem is in the file itself, but it seems to be okay. When I load it in pywb, it looks like this:
<img width="300" alt="pvda pywb" src="https://user-images.githubusercontent.com/16387089/184093274-5a0c1623-0e22-4d39-b5ce-9a5b0b933fcf.png">

Whereas when I load it in Solrwayback, it looks like this:
<img width="300" alt="pvda solrwayback" src="https://user-images.githubusercontent.com/16387089/184093200-f9365da5-1847-40ef-9798-914161d5a208.png">

Somehow, it looks like it is not loading the CSS and image files. When I look in my browser's console, I see a bunch of 404 errors. I tried it in Safari, Chrome and Firefox, but that does not make any difference.

The file can be found here: https://drive.google.com/file/d/18HlPVOWFf_QM4cY3BkI3cP4A_7Fu4rng/view?usp=sharing

Can you help me solve this problem? Thank you.

**Comment by thomasegense** [comment] 2022-08-17 10:58
For best playback in SolrWayback it is required to run under HTTPS. This will activate the serviceworker and it can fix live leaks
and redirect them back to the archive. (Guess your pywb also runs under https?)

**Comment by thomasegense** [comment] 2022-08-17 12:47
Looking into it...

**Comment by thomasegense** [comment] 2022-08-17 13:20
Confirmed.  The error is some of the image-urls of format 'data:image' 

When adding those to the solr-query to resolve multiple urls at once , the whole solr syntax constructed is invalid and will cause the query to fail. 

There are 2 errors at once:
1) The <img  src='xxxx'> should be ignored if starting with data:image 
2) Fix escaping in the combined solr-query. 

It should not be that hard to fix this bug, but still no guarantee it will fix playback.

**Comment by tokee** [comment] 2022-09-09 09:35
Accidentally closes as I committed to master instead of branch. Reopening...

**Comment by thomasegense** [comment] 2022-09-09 10:27
@mbreemhaar 
Hi, you can build newest snapshot from master or just download here:
https://drive.google.com/file/d/1JW4dKEQW1BmFCWldkJBd_53XDgftzeDp/view?usp=sharing

NOTICE you have too add this last line to solrwaybackweb.properties, or the propertyloader will fail during start:
about.text.file=/about_this_archive.txt 
search.help.text.file=/search_help.txt
**collection.text.file=/about_collection.txt**

This new collection info can by clicking the new look after the Toolbox icon.
Just as with the as about_this.archive.txt you can replace it will a file on the local drive and change the property to fullpath to that file.

**Comment by thomasegense** [comment] 2022-09-10 13:01
@mbreemhaar  confirmed fixed?

**Comment by mbreemhaar** [comment] 2022-09-10 13:20
Thanks a lot for looking into this!

Unfortunately it does not work like it should for me. The good thing is that the images are shown now, but the css does not seem to be loaded.

I saw this in the source code of the page it is loading. Maybe this helps: 
```<link media="all" href="http://localhost:8080/solrwayback/services/notfound/" rel="stylesheet">```

**Comment by thomasegense** [comment] 2022-09-10 13:33
If you click the playback toolbar and page resouces.
Then you can see the resource missing and try an url-search for it.
can you attach screenshot of the playback?

**Comment by mbreemhaar** [comment] 2022-09-10 13:37
The url search for the missing css does not find anything. This is what playback looks like for me now: 
![image](https://user-images.githubusercontent.com/16387089/189485851-2cf6ffcf-7319-4abf-95ac-bf6ca092d91f.png)

**Comment by thomasegense** [comment] 2022-09-10 14:07
It looked better for me. I will follow up on monday.

**Comment by thomasegense** [comment] 2022-09-11 15:22
@mbreemhaar Do we agree it is this page from your WARC file?
http://localhost:8080/solrwayback/services/web/20220707111526/https://www.pvda.nl/

I just downloaded the ROOT.war and solrwayback.war from the google drive link and I have attached the screenshot.
It looks correct to me


![www pvda nl](https://user-images.githubusercontent.com/5364348/189535313-81dbfeb5-f055-4fc4-9dd7-a6e0b646a30c.png)


Can you try call this serviceurl:
http://localhost:8080/solrwayback/services/frontend/properties/solrwaybackweb

And show me output,

**Comment by mbreemhaar** [comment] 2022-09-12 19:18
Something very strange is going on, because SolrWayback shows that the page has never been harvested if I click your link. I even tried removing the index, adding only the file I uploaded here and reindexing it. I'll look into why that is, because that must be a problem on my side. Unfortunately I don't have time tomorrow, but I will try to get back to you on wednesday.

The output of the service URL you gave me is the following:
`
{"leaflet.attribution":"&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors","top.left.logo.image":"http://localhost:8080/solrwayback/services/frontend/images/logo","wayback.baseurl":"http://localhost:8080/solrwayback/","wordcloud.stopwords":"[i, me, my, myself, we, our, ours, ourselves, you, your, yours, yourself, yourselves, he, him, his, himself, she, her, hers, herself, it, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, should, now]","leaflet.source":"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png","solrwayback.version":"4.3.1-SNAPSHOT","export.csv.fields":"id,index_time, author, description,keywords,description,license_url,content,content_encoding,content_length,content_language, content_type_droid,content_type_ext,content_type_full,content_type_norm,content_type_served,content_type_tika,content_type,content_type_version,elements_used,hash,wayback_date,crawl_year,url_norm,url_path,url,url_type,domain,host,host_surt,public_suffix,resourcename,image_size,links_images,links_domains,links_hosts,links_hosts_surts,links_norm,links_public_suffixes,links,server,status_code,generator,redirect_to_norm,source_file_path,source_file_offset,source_file,text,title,type,warc_key_id,warc_ip ,ssdeep_hash_bs_3, ssdeep_hash_bs_6, ssdeep_hash_bs_12, ssdeep_hash_bs_24, ssdeep_hash_bs_48, ssdeep_hash_bs_96,ssdeep_hash_bs_192","facets":"[domain, content_type_norm, type, crawl_year, status_code, public_suffix, status_code]","playback.disabled":"false","maps.radius":"50000","maps.longitude":"10.20","openwayback.baseurl":"http://web.archive.org/web/","webapp.baseurl":"/solrwayback/","allow.export.warc":"true","allow.export.csv":"true","archive.start.year":"1998","search.uploaded.file.disabled":"false","top.left.logo.image.link":"https://www.kb.dk/","maps.latitude":"56.17"}
`

**Comment by mbreemhaar** [comment] 2022-09-12 19:37
Thank you, that works! The page shows correctly now.

The page that does not load the stylesheets correctly is this one: http://localhost:8080/solrwayback/services/web/20220707132206/https://www.pvda.nl/?post_type=politici

What's also interesting is that when I load it for the first time it shows like in the screenshot I sent a few days ago, but after refreshing the page it shows a big black cross:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/16387089/189740083-79cbdbb9-d7b7-4f92-b7de-15171cd3386f.png">

If I clear my browser cache I can load the page once again without the cross. It could be a completely different problem, but I think it is part of some cookie agreement popup which does not load properly because of the missing CSS. (It also says "allow cookie management" in Dutch in the top left corner).

**Comment by thomasegense** [comment] 2022-09-12 19:42
I get the same result as  you. I will look into it tomorrow. Just the cross, also first time.

But sometimes if javascript expect cookies or stylesheets-url  are dynamic, then playback will not work.

**Comment by thomasegense** [comment] 2022-09-13 07:52
@mbreemhaar  I know what is going on now.

First of all, if you scroll down from the big X, then you will see the page below. ( in firefox)
If you open the page in chrome (maybe private mode), then it will not show the X.
Why it is so will take too much time tracking time and can probably not be fixed, since some sites
expect cookies to be set for the correct domain etc. Also there are some resources that had not been harvested.
I tried harvest the missing stylesheet and indexed it, but it did change anything.

Do you have the preview image working on the "page resources" page?  Because that does not show the big X
since the preview image is generated with headless chrome. Sometimes if the page looks better in the preview image try switch to the chrome browser.

I am closing this issue. Thanks for the jira's.

**Closed by thomasegense** 2022-09-13 07:52 UTC
