### ISSUE TITLE
Add caching in the SolrWayback-end

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#170] opened 2021-03-03 17:36 UTC
Obvious first search is `*:*` and it takes **forever**!

We should cache queries and we should auto-warm queries, just as Solr does, except that we should do it in the middle layer as Solr does not really cache facet calls properly.

**Comment by thomasegense** [comment] 2021-03-03 19:09
Duplicate of #63

**Closed by thomasegense** 2021-03-03 19:10 UTC
Labels: enhancement
